zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Products/SLE-Module-Basesystem/15-SP1/ppc64le/product/ SLE-Module-Basesystem_Product
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Products/SLE-Module-Containers/15-SP1/ppc64le/product/ SLE-Module-Containers_Product
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Products/SLE-Module-Development-Tools/15-SP1/ppc64le/product/ SLE-Module-Development-Tools_Product
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Products/SLE-Module-Legacy/15-SP1/ppc64le/product/ SLE-Module-Legacy_Product
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Products/SLE-Module-Python2/15-SP1/ppc64le/product/ SLE-Module-Python2_Product
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Products/SLE-Module-Server-Applications/15-SP1/ppc64le/product/ SLE-Module-Server-Applications_Product
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Products/SLE-Product-HA/15-SP1/ppc64le/product/ SLE-Product-HA_Product
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Products/SLE-Product-SLES/15-SP1/ppc64le/product/ SLE-Product-SLES_Product
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Updates/SLE-Module-Basesystem/15-SP1/ppc64le/update/ SLE-Module-Basesystem_Update
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Updates/SLE-Module-Containers/15-SP1/ppc64le/update/ SLE-Module-Containers_Update
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Updates/SLE-Module-Development-Tools/15-SP1/ppc64le/update/ SLE-Module-Development-Tools_Update
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Updates/SLE-Module-Legacy/15-SP1/ppc64le/update/ SLE-Module-Legacy_Update
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Updates/SLE-Module-Python2/15-SP1/ppc64le/update/ SLE-Module-Python2_Update
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Updates/SLE-Module-Server-Applications/15-SP1/ppc64le/update/ SLE-Module-Server-Applications_Update
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Updates/SLE-Product-HA/15-SP1/ppc64le/update/ SLE-Product-HA_Update
zypper addrepo http://suse-repo.spb.exe.com/repo/SUSE/Updates/SLE-Product-SLES/15-SP1/ppc64le/update/ SLE-Product-SLES_Update
